# Numpy
- Numerical Python 줄인말, 수치 연산 전용 라이브러리
- np.array(): 파이썬 리스트를 넘파이 배열(N-dimensional array)로 변환
- a.shape : 배열의 구조(차원)을 알려줌
- a.dtype : 배열 안의 데이터 타입

## 사용 목적
| 파이썬 리스트    | numpy 배열 |
|------------|------------|
| 일반적 연산에 적합 | 수치 계산에 특화 |
| for문 많이 씀 | 벡터화 연산 가능 (빠름!) |
| 느림 | 빠름 (C 기반) |
| 타입이 섞임 | 통일된 타입 (효율적 메모리) |


## ✅ 핵심 요약
- numpy.array는 고성능 배열
- 데이터 과학, AI, 행렬 연산 필수
- pandas도 내부적으로 numpy 기반


In [1]:
# 기본 배열 생성
import numpy as np

# 배열 생성
a = np.array([1, 2, 3, 4, 5])

print("Array a: ", a)
print("Type: ", type(a))
print("Shape: ", a.shape)

Array a:  [1 2 3 4 5]
Type:  <class 'numpy.ndarray'>
Shape:  (5,)


In [3]:
# 리스트 덧셈 (에러 아님, 결과는 붙이기)
a = [1, 2, 3] + [4, 5, 6]  # 결과: [1, 2, 3, 4, 5, 6]

# numpy 덧셈 (원소별 계산)
b = np.array([1, 2, 3]) + np.array([4, 5, 6])  # 결과: [5 7 9]

print("Array a: ", a)
print("Array b: ", b)


Array a:  [1, 2, 3, 4, 5, 6]
Array b:  [5 7 9]


In [4]:
# 연속 수열 생성

# 0 부터 9 까지 정수 생성
arr = np.arange(10)
print("\nArange array:", arr)

# 시작, 끝, 간격 지정
arr2 = np.arange(1, 11, 2)
print("Arange with step:", arr2)


Arange array: [0 1 2 3 4 5 6 7 8 9]
Arange with step: [1 3 5 7 9]


In [6]:
# 배열 모양 바꾸기

# 1차원 배열을 2차원으로 변#
arr = np.arange(12)
reshaped_arr = arr.reshape(3, 4)
print("\nReshaped array:\n", reshaped_arr)


Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
# Numpy Slicing

# 1차원 슬라이싱
arr = np.arange(10)
print("\nOriginal array:\n", arr)
print("Slice 2 to 5: ", arr[2:5])


# 2차원 슬라이싱
matrix = np.arange(1, 13).reshape(3, 4) # 1~12까지 1차원 배열 생성후 3*4배열로 변환
print("\nMatrix:\n", matrix)
print("First two rows and first two columns:\n", matrix[:2, :2])
print("Last row:\n", matrix[-1, :])



Original array:
 [0 1 2 3 4 5 6 7 8 9]
Slice 2 to 5:  [2 3 4]

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First two rows and first two columns:
 [[1 2]
 [5 6]]
Last row:
 [ 9 10 11 12]


In [9]:
# Numpy 정수 인덱싱 - 특정 위치의 값 선택
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("\nMatrix:\n", matrix)

selected = matrix[[0, 1, 2], [0, 1, 2]]
print("\nSelected values (diagonal):\n", selected)

selected2 = matrix[[0, 1, 2], [2, 0, 1]]
print("\nSelected values :\n", selected2)


Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Selected values (diagonal):
 [10 50 90]

Selected values :
 [30 40 80]


In [10]:
# 기본 산술 연산
arr = np.array([1, 2, 3, 4, 5])
print("\nOriginal array:", arr)
print("Add 10:", arr + 10)
print("Multiply by 2:", arr * 2)
print("Square:", arr ** 2)


arr2 = np.array([5, 4, 3, 2, 1])
print("\nArray 2:", arr2)
print("Addition:", arr + arr2)
print("Multiplication:", arr * arr2)


Original array: [1 2 3 4 5]
Add 10: [11 12 13 14 15]
Multiply by 2: [ 2  4  6  8 10]
Square: [ 1  4  9 16 25]

Array 2: [5 4 3 2 1]
Addition: [6 6 6 6 6]
Multiplication: [5 8 9 8 5]


In [11]:
# Numpy 논리 인덱싱 - 조건 필터링

arr = np.arange(10)
print("\nOriginal array:", arr)

# 5보다 큰 값만
filtered = arr[arr > 5]
print("Value greater than 5:", filtered)

# 짝수만
even = arr[arr % 2 == 0]
print("\nEven numbers:", even)


Original array: [0 1 2 3 4 5 6 7 8 9]
Value greater than 5: [6 7 8 9]

Even numbers: [0 2 4 6 8]
